# Generated by Django 5.2.7 on 2025-12-10 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espectro_cores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cor_correta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espectro_cores.cor')),
            ],
        ),
    ]
